Quoted all variables that don't actively need to not be in passman

diff --git a/passman b/passman
--- a/passman
+++ b/passman
@@ -2,9 +2,9 @@
 
 set -e
 
-realbin=$(readlink -f $0)
+realbin=$(readlink -f "$0")
 
-cd $(dirname $realbin)
+cd $(dirname "$realbin")
 
 API="cryptapi.sh"
 LEGAL_CHARS="[[:alnum:]_-]"
@@ -13,21 +13,21 @@ UTOKEN=""
 
 ATOKEN=""
 
-SCRIPT=$0
+SCRIPT="$0"
 
-. $API
+. "$API"
 
 # Enable command line editing, history and completion
 if [ -z "$RLWRAP_RUNNING" ] && which rlwrap >/dev/null &&
     [ "$(id -un)" != passman ]; then
-    EXTRA_COMP=$HOME/.passman_completions
-    list-passwords > $EXTRA_COMP
+    EXTRA_COMP="$HOME"/.passman_completions
+    list-passwords > "$EXTRA_COMP"
     export RLWRAP_RUNNING=1
-    exec rlwrap -C passman -b '' -f completions -f $EXTRA_COMP $realbin "$@"
+    exec rlwrap -C passman -b '' -f completions -f "$EXTRA_COMP" "$realbin" "$@"
 fi
 
 [ ! "$(id -un)" = "passman" ] && [ -z "$PASSMAN_TEST" ] && {
-    exec sudo -u passman $realbin "$@"
+    exec sudo -u passman "$realbin" "$@"
 }
 
 function assist {
@@ -35,7 +35,7 @@ function assist {
     then
 	cat help/passman
     else
-	cat help/$1 2>/dev/null || { echo "That is not a command."; return 1; }
+	cat help/"$1" 2>/dev/null || { echo "That is not a command."; return 1; }
     fi
     echo
     return 0
@@ -50,22 +50,22 @@ function validate {
     then
 	read -sp "${UNAME}'s Password: " pw
 	echo
-	UTOKEN=$(decrypt user/$UNAME "$pw")
+	UTOKEN=$(decrypt user/"$UNAME" "$pw")
 	local result=$?
 	unset pw
 	if [ "$result" != "0" ]
 	then
 	    echo "Password incorrect."
 	fi
-	return $result
+	return "$result"
     fi
 }
 
 function validate-admin {
     validate
-    if [ -z $ATOKEN ]
+    if [ -z "$ATOKEN" ]
     then
-	ATOKEN=$(decrypt group/admin.$UNAME $UTOKEN)
+	ATOKEN=$(decrypt group/admin."$UNAME" "$UTOKEN")
     fi
     return $?
 
@@ -75,7 +75,7 @@ function menu {
     local action=""
 
     # change window title
-    printf "\033]0;passman@$(hostname)\007"
+    printf "\033]0;passman@%2\007" "$(hostname)"
 
     while true
     do
@@ -90,7 +90,7 @@ function menu {
 		assist
 		;;
 	    * )
-		execute $action || true
+		execute "$action" || true
 		;;
 	esac
     done
@@ -115,7 +115,7 @@ function execute {
 	return 1
     fi
     
-    local action=$1
+    local action="$1"
     shift
 
     local type=""
@@ -127,7 +127,7 @@ function execute {
     case "$action" in
 	get )
 	    validate || return $?
-	    show-pass $UNAME $UTOKEN "$1" || { echo "$UNAME cannot access $1." && return 1; }
+	    show-pass "$UNAME" "$UTOKEN" "$1" || { echo "$UNAME cannot access $1." && return 1; }
 	    return 0
 	    ;;
 	list )
@@ -147,40 +147,40 @@ function execute {
 		    return $?
 		    ;;
 	    esac
-	    local regex=$2
+	    local regex="$2"
 	    
-	    printf "$(list-$type | tr ' ' '\n' | grep -E "$regex")\n"
+	    printf "%s\n" "$(list-"$type" | tr ' ' '\n' | grep -E "$regex")"
 	    return 0
 	    ;;
 	
 	info )
 	    case "$1" in
 		user )
-		    name=$2
+		    name="$2"
 		    
 		    echo
 		    echo "$name is in the following groups:"
-		    list-user-groups $name
+		    list-user-groups "$name"
 		    echo
 		    echo "$name can access the following passwords:"
-		    list-available $name
+		    list-available "$name"
 		    echo
 		    return 0
 		    ;;
 		group )
-		    name=$2
+		    name="$2"
 		    
 		    echo
 		    echo "$name has the following members:"
-		    list-group-users $name
+		    list-group-users "$name"
 		    echo
 		    echo "$name contains the following passwords:"
-		    list-group-passes $name
+		    list-group-passes "$name"
 		    echo
 		    return 0
 		    ;;
 		pass )
-		    name=$2
+		    name="$2"
 		    
 		    echo "$name belongs to the following groups:"
 		    list-password-groups $name
@@ -193,10 +193,10 @@ function execute {
 	    esac
 	    ;;
 	manage )
-	    type=$1
-	    name=$2
-	    action=${3:0:1}
-	    member=${3:1}
+	    type="$1"
+	    name="$2"
+	    action="${3:0:1}"
+	    member="${3:1}"
 	    local message=""
 	    
 	    case "$type" in
@@ -226,7 +226,7 @@ function execute {
 	    esac
 	    
 	    validate-admin || return $?
-	    ${action}$type $ATOKEN $name $member
+	    ${action}$type "$ATOKEN" "$name" "$member"
 	    local result=$?
 	    case "$result" in
 		"0" )
@@ -242,11 +242,11 @@ function execute {
 		    echo "An error occurred."
 		    ;;
 	    esac
-	    return $result
+	    return "$result"
 	    ;;
 	add|del )
-	    type=$1
-	    name=$2
+	    type="$1"
+	    name="$2"
 	    local message=""
 	    case "$action" in
 		"add" )
@@ -275,9 +275,9 @@ function execute {
 			    
 			    if [ -z "$EDITOR" ]
 			    then 
-				editor $tmpfile
+				editor "$tmpfile"
 			    else
-			        $EDITOR $tmpfile
+			        "$EDITOR" "$tmpfile"
 			    fi
 			    
 			    if [ -s "$tmpfile" ]
@@ -301,24 +301,24 @@ function execute {
 	    esac
 	    
 	    validate-admin || return $?
-	    ${action}"-"$type $ATOKEN $name "$pass"
+	    ${action}"-"$type "$ATOKEN" "$name" "$pass"
 	    echo "$type '$name' successfully "$([ "$action" = "add" ] && echo "added" || echo "removed")"." 
 	    return $?
 	    ;;
 	modify )
-	    local pname=$1
+	    local pname="$1"
 	    validate-admin || return $?
 
 	    tmpfile="tmp-$(date +%y%m%d%H%M%S)"
 	    touch "$tmpfile"
 	    chmod 600 "$tmpfile"
-	    show-pass $UNAME $UTOKEN $pname > $tmpfile
+	    show-pass "$UNAME" "$UTOKEN" "$pname" > "$tmpfile"
 
 	    if [ -z "$EDITOR" ]
 	    then 
-		editor $tmpfile
+		editor "$tmpfile"
 	    else
-		$EDITOR $tmpfile
+		"$EDITOR" "$tmpfile"
 	    fi
 	    
 	    if [ -s "$tmpfile" ]
@@ -332,7 +332,7 @@ function execute {
 		return 1
 	    fi
 	    
-	    modify-pass $ATOKEN $pname "$pass"
+	    modify-pass "$ATOKEN" "$pname" "$pass"
 	    echo "Pass '$pname' successfully updated."
 	    return 0
 	    ;;
@@ -346,36 +346,36 @@ function execute {
 	    read -sp "Retype password: " pass2
 	    echo
 
-	    [ "$pass1" = "$pass2" ] && change-user-pass $UTOKEN $UNAME $pass1
+	    [ "$pass1" = "$pass2" ] && change-user-pass "$UTOKEN" "$UNAME" "$pass1"
 	    result=$?
 
 	    unset pass1
 	    unset pass2
 	    
 	    [ "$result" = "0" ] && echo "Your password has been changed."
-	    return $result
+	    return "$result"
 	    ;;
 	promote )
 	    name=$1
 	    validate-admin || return $?
-	    make-user-admin $ATOKEN $name
+	    make-user-admin "$ATOKEN" "$name"
 	    echo "'$name' is now an administrator."
 	    return 0
 	    ;;
 	demote )
-	    name=$1
+	    name="$1"
 	    validate-admin || return $?
 	    if [ "$name" == "$UNAME" ]
 	    then
 		echo "You cannot demote yourself, not doing anything."
 		return 1
 	    fi
-	    unmake-user-admin $ATOKEN $name
+	    unmake-user-admin "$ATOKEN" "$name"
 	    echo "'$name' is no longer an administrator."
 	    return $?
 	    ;;
 	'help' )
-	    assist $1
+	    assist "$1"
 	    ;;
 	"" )
 	    return 0
@@ -393,11 +393,11 @@ do
     shift
     case "$var" in
 	u )
-	    UNAME=$1
+	    UNAME="$1"
 	    shift
 	    ;;
 	e )
-	    EDITOR=$1
+	    EDITOR="$1"
 	    shift
 	    ;;
 	* )
